# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20170427_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('banner', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='form_banners', verbose_name='Banner')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='form',
            name='terms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=1020, null=True, verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='formslist',
            name='forms',
            field=models.ManyToManyField(related_name='Form', to='forms.Form'),
        ),
    ]
