# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20170428_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='terms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('a', 'b')], max_length=255, null=True, verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='formslist',
            name='forms',
            field=models.ManyToManyField(related_name='formslist', to='forms.Form'),
        ),
    ]
