# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20170428_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formslist',
            name='forms',
        ),
        migrations.AddField(
            model_name='form',
            name='forms_list',
            field=models.ManyToManyField(related_name='forms', to='forms.FormsList', blank=True, null=True),
        ),
    ]
