# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20170428_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalFormEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('banner', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='form_banners', verbose_name='Banner')),
                ('url', models.CharField(max_length=511, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'External form',
                'verbose_name_plural': 'External forms',
            },
        ),
    ]
