# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-09 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20170609_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalformentry',
            name='forms_list',
            field=models.ManyToManyField(blank=True, related_name='external_forms', to='forms.FormsList'),
        ),
    ]
