# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20170614_0224.py'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractform',
            name='email_from',
        ),
    ]
