# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-13 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20170614_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='email_from',
        ),
    ]
